### ISSUE TITLE
Edit button not visible

### ISSUE THREAD

**Issue by EdaU** [NodeBB/nodebb-theme-community#20] opened 2021-12-08 19:59 UTC
![image](https://user-images.githubusercontent.com/8782704/145275880-f683241b-a780-4f2c-b21c-478cb67099a4.png)

**Comment by julianlam** [comment] 2021-12-08 21:39
Ah @EdaU, sorry, I am going to have to `WONTFIX` this as it is by design :grimacing: 

The bootstrap style has the dropdown menu with a z-index of `1000` and the fixed navbar with z-index `1030`, that is why it is on top.

Normally the dropdown will open _downwards_, but in your case is opening upwards because I think, of limited vertical screen space.

When I go to that topic and open the dropdown it opens downwards for me :shrug:

**Closed by julianlam** 2021-12-08 21:39 UTC
